### ISSUE TITLE
Bad multivariate normal random covariate

### ISSUE THREAD

**Issue by MurrayEfford** [eMoqanaki/HeterogeneousDetectionSCR#1]
The code in SimulateAutocorrelatedRaster.R has the line for the Cholesky decomposition in rmvn() commented out
    #D <- chol(V)
and replaced by
    D <- V

This change is not innocent - it changes the simulated values and increases Moran's I. For example, I get I = 0.83 for scenario 4, whereas Appendix II has I = 0.95.

Was there a reason? With D <- chol(V), rmvn() gives results comparable to mvtnorm::rmvtnorm(), which would have been a better choice.

**Comment by eMoqanaki** [comment]
@MurrayEfford We intended to simulate scenarios with highly spatially autocorrelated detection covariates where Moran's I is closer to 1; this was not possible using the chol(D) matrix. However, we repeated most of these scenarios with D <- chol(V) in a [second study](https://doi.org/10.1016/j.ecolmodel.2023.110324).

**Comment by MurrayEfford** [comment]
Thanks for your response. I suspected as much, and I can now reproduce your results. The paper could be accused of misleading, as it says you used MVN and Guelat (2013). It's hard enough to follow the methods without laying traps like that! Are you saying the ad hoc distribution was needed because it is not possible to model strong autocorrelation with MVN? Once I understood it, the switch to a uniform distribution is a nice trick that removes some unwanted variation - you are just using the quasi-MVN to generate a spatial pattern, not magnitudes.
Murray
________________________________

**Comment by MurrayEfford** [comment]
You can get Moran's I around 0.945 with a squared-exponential covariance structure

**Comment by eMoqanaki** [comment]
@MurrayEfford Thanks for the comment. Yes, we were aiming to generate specific spatial patterns with a certain level of spatial autocorrelation based on what we suspected in some real-life studies. Modifying the Guélat's function seemed an easy fix to achieve this at the time. We mentioned that we modified the function and also provided the code: "... using a function developed by Guélat (2013), with minor modifications (Online Appendix 1)". However, I agree that we should have been clear about this step and the quasi-multivariate normal distribution in the paper.

**Comment by MurrayEfford** [comment]
Trying to tie this up - I find that using a squared-exponential covariance structure (cov_ij = exp(-phi^2 d_ij^2) with MVN randoms gives almost exactly the same results as yours with the modified MVN, and perhaps they are mathematically equivalent. Squared-exponential happens to be the covariance structure emphasised by Ben Stevenson in his Biometrics paper.

scenario nvalid     RB   RSE  COV
       1    100 -0.084 0.064 0.66
       2    100 -0.007 0.065 0.94
       3    100  0.002 0.065 0.95
       4    100 -0.320 0.053 0.00
       5    100 -0.023 0.049 0.93
       6    100  0.004 0.048 0.97

RB(D-hat) and RSE(D-hat) (='CV') are means, not medians. Results for Scenario 5 are a bit different to Moqanaki et al 2021 Appendix 2, but not worth pursuing.
